### ISSUE TITLE
PUBKEY_SSH_FIRST_USER parameter

### ISSUE THREAD

**Issue by ruzickap** [usimd/pi-gen-action#119]
Would it be possible to add `PUBKEY_SSH_FIRST_USER` parameter like it is described here?

https://github.com/RPi-Distro/pi-gen/blob/f1c166a2833950a7c44fe19b01780723635a7aa3/README.md?plain=1#L185

Thank you...

**Comment by usimd** [comment]
Thanks for reaching out!

Definitely possible, some of the bits and pieces are already in place: 
https://github.com/usimd/pi-gen-action/blob/6f631e5a090466b6b1c54a7b92e45699d9f00b85/src/pi-gen-config.ts#L25-L26

These would need to be exposed as inputs in the `action.yaml` and be mapped accordingly here https://github.com/usimd/pi-gen-action/blob/6f631e5a090466b6b1c54a7b92e45699d9f00b85/src/configure.ts#L46

Following the spirit of this action, some input validation should be added to fail fast. The syntax of the pubkey should be checked. The cipher used could be with a regex against a whitelist, to verify the public key, there is hopefully some dependency (like https://www.npmjs.com/package/ssl-validator, although at first sight there's no matching function).

Are you interested in creating a PR for this?

**Comment by ruzickap** [comment]
I'm really sorry, but I do not know the TypeScript :-(
