### ISSUE TITLE
need arg for ARCHIVE_FILENAME 

### ISSUE THREAD

**Issue by misogihagi** [usimd/pi-gen-action#129]
https://github.com/RPi-Distro/pi-gen/blob/master/build.sh#L187

**Is your feature request related to a problem? Please describe.**
I have to control file name. ARCHIVE_FILENAME and IMG_SUFFIX is trick to name. But pi-gen-action does not have it.

**Describe the solution you'd like**
implementing of arguments corresponding to ARCHIVE_FILENAME and IMG_SUFFIX.

**Comment by usimd** [comment]
Thanks for reaching out.

This has been discussed in https://github.com/usimd/pi-gen-action/issues/53 already. I still don't see the need to make this action a "all-in-one" solution, this is what GitHub Actions are designed for, i.e. to add customization to larger building blocks.

If you see any additional points I haven't considered so far, feel free to reopen.
