### ISSUE TITLE
add "archive_filename" variable

### ISSUE THREAD

**Issue by builderjer** [usimd/pi-gen-action#53]
**Is your feature request related to a problem? Please describe.**

When an image is built, pi-gen automatically adds a date to the 'image_name' variable
`image_name: my_image`
results in an image named
`image_2023-03-23-my_image.img`

**Describe the solution you'd like**

I would like to have another variable available in this action that is available in the pi-gen config file.
the `ARCHIVE_FILENAME` variable shown [here](https://github.com/RPi-Distro/pi-gen/blob/f2d385517c9631f2ded876deb1115725d0c75995/build.sh#L206) lets one set the final image name with what ever prefix/suffix that the user wants.

**Describe alternatives you've considered**

An alternative would be to fork the [RPi-Distro/pi-gen](https://github.com/RPi-Distro/pi-gen) repository and maintain a fork just to get a custom image name.

**Additional context**

I would fork this and do a PR, but I am not familiar with how all of these work exactly.  If a change is made, I can compare the changes and learn how to fix/add and PR upstream

**Comment by usimd** [comment]
Thanks for reaching out and for your suggestion! I actually understand the need to customize the file name.

Before making changes in the code, I see two other options that could immediately support the case.

1. After invoking `pi-gen-action` in your workflow, you could add another step to simply rename the file on disk, that shouldn't be a biggy.
2. You could try to pass `ARCHIVE_FILENAME` as additional `docker-opts` to `pi-gen-action`. Similar to https://github.com/usimd/pi-gen-action/issues/43, this will set the environment variable inside the container so the build script should be able to pick it up.

Would you mind trying either one of those options before thinking about a code change?

**Comment by builderjer** [comment]
I will test this when I run another action on this image.  Still trying to work out a few bugs on the local version.  Thank you very much for such a quick response

**Comment by usimd** [comment]
Sure, you're welcome. Let me know how this works out.

**Comment by builderjer** [comment]
option 2 did not work for me.  It complained about capitalization.  I will try option 1 later.  I am not very familiar with actions yet

**Comment by builderjer** [comment]
I found a work around that is perfect.  I will close this now.  Thanks for your help and quick responses

**Comment by florian-asche** [comment]
> I found a work around that is perfect. I will close this now. Thanks for your help and quick responses

do you mind, sharing your workaround?
