### ISSUE TITLE
Adding a custom stage `stage4a` fails

### ISSUE THREAD

**Issue by probonopd** [usimd/pi-gen-action#98]
**Describe the bug**
I would like to add a custom stage `stage4a` after the default `stage4`.

**To Reproduce**

```
stage-list: stage0 stage1 stage2 stage3 stage4 ./stage4a
```

https://github.com/probonopd/custom-raspberry-pi-os/blob/cd0ee0734602d6b910976373c57ae3ed308ec67d/.github/workflows/pi-gen.yml#L21

or

```
stage-list: stage0 stage1 stage2 stage3 stage4 stage4a
```

https://github.com/probonopd/custom-raspberry-pi-os/blob/65a99d75c62a424ab3a626e4a3d3c7e1e5b07cfb/.github/workflows/pi-gen.yml#L21

**Expected behavior**
`stage0 stage1 stage2 stage3 stage4` run from the default pi-gen, then my custom `stage4a` runs from my repository

**Logs**
```
Run usimd/pi-gen-action@v1
Validating input and generating pi-gen config
Error: stage-list must contain valid pi-gen stage names "stage[0-5]" and/or valid directories
```
* https://github.com/probonopd/custom-raspberry-pi-os/actions/runs/6995539883/job/19030500707

**Additional context**
Please document a simple example where a custom stage is run after the default stages.

**Comment by usimd** [comment]
From your linked workflow file, it seems you've missed to add a checkout step of your own repository. That's not being done implicitly by the action.

To verify things initially, it could help to add a step
```yaml
- run: tree
```
That way you can inspect the local working directory on the action runner. If you're custom stage dir is missing there, it cannot be found by `pi-gen-action`.

**Comment by probonopd** [comment]
Thank you very much @usimd.
